build:
  stage: build
  image: ubuntu:trusty
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - apt-get update
    - apt-get install -y ant dvipng perl python-imaging rubber texlive-fonts-recommended texlive-latex-extra texlive-math-extra wget
    - wget "https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz"
    - shasum -a 512 -c - <<< "c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0 *apache-maven-3.6.3-bin.tar.gz"
    - tar -zxvf apache-maven-3.6.3-bin.tar.gz
    - export M2_HOME="${PWD}/apache-maven-3.6.3"
    - export PATH="${M2_HOME}/bin:$PATH"
    - wget -O plastex.tar.gz https://github.com/tiarno/plastex/archive/1.0.0.tar.gz
    - tar -xzvf plastex.tar.gz
    - (cd plastex-1.0.0 && python setup.py install)
  script:
    - cd org.rodinp.handbook.feature
    - ant -file customBuild.xml
    - cd ..
    - cp -r org.rodinp.handbook.feature/build/eclipse/* org.rodinp.handbook/
    - mvn -f org.rodinp.handbook.parent/pom.xml install
    - cp org.rodinp.handbook.releng/index.html org.rodinp.handbook.repository/target/repository
  artifacts:
    paths:
      - org.rodinp.handbook.feature/build
      - org.rodinp.handbook.repository/target/repository
