build:
  stage: build
  image: ubuntu:trusty
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y ant dvipng maven python-imaging rubber texlive-fonts-recommended texlive-latex-extra texlive-math-extra wget
    - wget -O plastex.tar.gz https://github.com/tiarno/plastex/archive/1.0.0.tar.gz
    - tar -xzvf plastex.tar.gz
    - cd plastex-1.0.0 && sudo python setup.py install
  script:
    - cd org.rodinp.handbook.feature
    - ant -file customBuild.xml
    - cd ..
    - cp -r org.rodinp.handbook.feature/build/eclipse/* org.rodinp.handbook/
    - mvn -f org.rodinp.handbook.parent/pom.xml install
    - mkdir -p upload/current
    - cp -r org.rodinp.handbook.feature/build/files upload/current/
    - cp -r org.rodinp.handbook.feature/build/html upload/current/
    - cp -r org.rodinp.handbook.feature/build/pdf upload/current/
    - mkdir -p upload/updatesite
    - cp -r org.rodinp.handbook.repository/target/repository/* upload/updatesite/
    - cp org.rodinp.handbook.releng/index.html upload/updatesite/
  artifacts:
    paths:
      - upload
